### ISSUE TITLE
Permission for setting labels

### ISSUE THREAD

**Issue by inson1** [artyommironov/nanji#20]
May you give permission to normal users to set labels?

**Comment by artyommironov** [comment]
I think normal users [can't](https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner/13829505#13829505) set labels in Github. There is an option to to have issue templates, but IMO it's overkill for this project.

**Comment by inson1** [comment]
@artyommironov yea you right. I thought I saw it somewhere, but it was probably just a mobile app with a bug
![Screenshot_2023-10-18-13-49-30-421_com.github.android.jpg](https://github.com/artyommironov/nanji/assets/75314629/871119b3-6066-4796-b937-edafd9c246ea)

![Screenshot_2023-10-18-13-49-44-053_com.github.android.jpg](https://github.com/artyommironov/nanji/assets/75314629/117841e5-0d4e-4ec7-975c-9980323bfa9b)
