### ISSUE TITLE
Widget not updating properly

### ISSUE THREAD

**Issue by aero31aero** [artyommironov/nanji#21]
When it behaves like this, the widget updates when I click on it, but otherwise appears to be stuck.

![Screenshot_20230904-194233.png](https://github.com/artyommironov/nanji/assets/8033238/4cc68a86-e942-430a-a2dd-0c2df81528d1)

See screenshot for example of another clock widget and the system clock being in sync but this one showing an outdated time. The Korean time reads 37 minutes in the screenshot.

**Comment by inson1** [comment]
Maybe you didnt allow nanji to work in background or you didnt opt out nanij from battery optimization?

**Comment by inson1** [comment]
@aero31aero Did you resolve your issue?

**Comment by inson1** [comment]
@aero31aero https://dontkillmyapp.com

**Comment by inson1** [comment]
@artyommironov I think It's time to close this issue. It's been a month already and @aero31aero didnt respond.

**Comment by aero31aero** [comment]
Sorry, I got busy with life. I implemented this suggestion 2 days ago and haven't seen the bug yet. Between the battery optimisation and the new update, this is fixed!
