### ISSUE TITLE
Simplified Chinese uses the wrong character for zero in years

### ISSUE THREAD

**Issue by Nekronek0** [artyommironov/nanji#4]
The character 零 is used in years in this app ( version 1.3.3) Afaik this should be 〇，in simplified Chinese atleast.
![Screenshot_20210408-111035~2](https://user-images.githubusercontent.com/13585444/114000285-24b1a580-985b-11eb-94ec-731202837962.png)

**Comment by artyommironov** [comment]
Fixed in 1.4.0
