### ISSUE TITLE
Add option for time to be above date

### ISSUE THREAD

**Issue by darkralts** [artyommironov/nanji#6]
I likenit with big time on top, and date under time. Pls add feature as it will look 100009% better, thank you :) have a fantastic evening.

**Comment by inson1** [comment]
@artyommironov I agree that it would be great feature. What are you thinking?

**Comment by artyommironov** [comment]
I agree. It requires to adjust "Appearance" screen:
- need to rework widget preview to show both date and time
- need to add a switch like "Show time first"

**Comment by inson1** [comment]
@artyommironov Why cant be there 4. option for display mode instead of a switch? Date and time, Time and Date, Date only, Time only?

**Comment by inson1** [comment]
@artyommironov When do you plan to add new version of the app to Google play And f-droid?

**Comment by artyommironov** [comment]
Already on Google Play, I think f-droid will add it automatically.

**Comment by inson1** [comment]
Okay, I just had to restart my phone
